name: Test Actions

on: [push]
jobs:
    Compila-Java:
        strategy:
          matrix:
            java: [ '8', '11', '17' ]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository 
          uses: actions/checkout@v4
        - run: ls -ltr
        - name: Setup java
          uses: actions/setup-java@v5.1.0
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
            
        - name: Build App
          run: javac Codigo/HelloWorldApp.java
        - run: ls -ltr Codigo
        - name: Run App
          run: java -cp Codigo HelloWorldApp
          
        - run: echo "Test finished"
        
