name: Test Actions

on: [push]
jobs:
    Imprimir-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository 
          uses: actions/checkout@v4
        - run: ls -ltr
        - name: Setup java
          uses: actions/setup-java@v5.1.0
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '19'
        - run: java Codigo/HelloWorldApp.java
        - run: echo "Hello world"
        
