name: Test Actions

on: [push]
jobs:
    Imprimir-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-java@v5.1.0
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '19'
        - run: java HelloWorldApp.java
        - run: echo "Hello world"
        
